# Spring
spring.main.banner-mode: "off"

# Log
logging:
  level.org:
    hibernate:
      SQL: WARN
      type:
        descriptor.sql.BasicBinder: WARN
        value: WARN
      value: WARN
    springframework.web: WARN

spring.jpa:
  show-sql: false
  open-in-view: false

# Server
server:
  port: 8080

# H2 Database
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
